name: PyPI 📦 Distribution

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        platform: [x64]
    steps:
    - name: Set up system path for python libs.
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Set up MSVC
      if: matrix.os == 'windows-latest'
      uses: microsoft/setup-msbuild@v1

    - name: Set up MSVC CMD x86_64
      if: matrix.os == 'windows-latest' && matrix.platform == 'x64'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    
    - name: Set up MSVC CMD x86
      if: matrix.os == 'windows-latest' && matrix.platform == 'x32'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Install dependencies
      run: |
        python3 -m pip install setuptools wheel meson

    - name: Clone latest radare2
      run: git clone https://github.com/radareorg/radare2

    - name: Remove link.exe to avoid conflicts and Build distribution 📦 on Windows
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
          del /f "C:\Program Files\Git\mingw64\bin\link.exe"
          python3 setup.py bdist_wheel
      
    - name: Build distribution 📦
      if: matrix.os != 'windows-latest'
      shell: bash
      run: python3 setup.py bdist_wheel
    
    - name: Test our build
      run: python3 -m pip install -e . && cd tests && python3 test_rapi.py
  
    - uses: actions/upload-artifact@v2
      with:
         path: ${{ github.workspace }}/dist/*

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_pass }}
